# Generated by Django 5.2.1 on 2026-02-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal nickname or label for the building (e.g., 'Astoria Duplex').",
                        max_length=200,
                    ),
                ),
                (
                    "building_type",
                    models.CharField(
                        choices=[
                            ("SFH", "Single Family"),
                            ("MULTI_FAMILY", "Multi-Family"),
                            ("CONDO", "Condo"),
                            ("TOWNHOUSE", "Townhouse"),
                            ("MIXED_USE", "Mixed Use"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="High-level building category used for reporting and defaults.",
                        max_length=32,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Street address line 1.",
                        max_length=255,
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Street address line 2 (apt/suite).",
                        max_length=255,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", help_text="City.", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="State / province / region.",
                        max_length=100,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Postal/ZIP code.",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO-3166 alpha-2 country code (e.g., US).",
                        max_length=2,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last updated timestamp."
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Owning organization (tenant). Derived from request.org on create.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Unit label/number (e.g., '1A', 'Unit 2', 'Downstairs').",
                        max_length=50,
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of bedrooms (optional).",
                        null=True,
                    ),
                ),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Number of bathrooms (optional). Use .50 for half baths.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "sqft",
                    models.PositiveIntegerField(
                        blank=True, help_text="Square footage (optional).", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last updated timestamp."
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        help_text="Parent building that contains this unit.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="buildings.building",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Owning organization (tenant). Derived from request.org on create.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["organization", "created_at"],
                name="buildings_b_organiz_2d4e0d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["organization", "name"], name="buildings_b_organiz_3e1534_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_building_name_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["organization", "building"],
                name="buildings_u_organiz_8dadda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["organization", "label"], name="buildings_u_organiz_19fec0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("building", "label"), name="uniq_unit_label_per_building"
            ),
        ),
    ]
