# Generated by Django 5.2.11 on 2026-02-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="address_line1",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Street address line 1.",
                max_length=255,
                null=True,
            ),
        ),
    ]
