# Generated by Django 5.2.11 on 2026-02-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0002_alter_building_address_line1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="address_line2",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Street address line 2 (apt/suite).",
                max_length=255,
                null=True,
            ),
        ),
    ]
