# Generated by Django 5.2.1 on 2026-02-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("rent_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "security_deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("rent_due_day", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="core.organization",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leases",
                        to="buildings.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=32, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenants",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaseTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("co_tenant", "Co-tenant"),
                            ("occupant", "Occupant"),
                        ],
                        default="primary",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease_tenants",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lease_links",
                        to="leases.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["organization", "created_at"],
                name="leases_leas_organiz_00e567_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["organization", "unit"], name="leases_leas_organiz_66f33b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["organization", "status"], name="leases_leas_organiz_6ea869_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["organization", "unit", "status"],
                name="leases_leas_organiz_3ee043_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("organization", "unit"),
                name="uniq_active_lease_per_unit_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["organization", "created_at"],
                name="leases_tena_organiz_c84e4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["organization", "full_name"],
                name="leases_tena_organiz_2d39dd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("organization", "email"),
                name="uniq_tenant_email_per_org_when_present",
            ),
        ),
        migrations.AddIndex(
            model_name="leasetenant",
            index=models.Index(
                fields=["organization", "lease"], name="leases_leas_organiz_c1d888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leasetenant",
            index=models.Index(
                fields=["organization", "tenant"], name="leases_leas_organiz_6b988a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leasetenant",
            constraint=models.UniqueConstraint(
                fields=("lease", "tenant"), name="uniq_tenant_per_lease"
            ),
        ),
        migrations.AddConstraint(
            model_name="leasetenant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "primary")),
                fields=("lease",),
                name="uniq_primary_tenant_per_lease",
            ),
        ),
    ]
