# Generated by Django 5.2.11 on 2026-02-14 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe unique identifier for the organization.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-disable org access without deleting data.",
                    ),
                ),
                (
                    "default_timezone",
                    models.CharField(
                        default="America/New_York",
                        help_text="Default timezone used for reporting periods and UI display.",
                        max_length=64,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="ISO-4217 currency code for reporting (MVP: USD).",
                        max_length=3,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="core_organi_slug_517c11_idx"),
                    models.Index(
                        fields=["is_active"], name="core_organi_is_acti_9518a1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("accountant", "Accountant"),
                            ("read_only", "Read Only"),
                        ],
                        help_text="Role determines allowed actions within the organization.",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        help_text="Membership lifecycle state (invited/active/suspended).",
                        max_length=16,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-disable membership without deleting historical records.",
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the invitation was created.",
                        null=True,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when membership became active.",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional: last time the user used the org (good for admin UX).",
                        null=True,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who invited this member (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "user"],
                        name="core_organi_organiz_3e713d_idx",
                    ),
                    models.Index(
                        fields=["organization", "role"],
                        name="core_organi_organiz_99a70a_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="core_organi_organiz_da3f73_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_active"],
                        name="core_organi_organiz_12c291_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user"), name="uniq_member_per_org"
                    )
                ],
            },
        ),
    ]
