# Generated by Django 5.2.11 on 2026-03-15 23:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0003_alter_building_address_line2"),
        ("core", "0001_initial"),
        ("leases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable category name within the organization.",
                        max_length=120,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable slug used for filtering and programmatic references.",
                        max_length=140,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("operating", "Operating"),
                            ("capital", "Capital"),
                            ("admin", "Admin"),
                            ("tax", "Tax"),
                            ("insurance", "Insurance"),
                            ("utilities", "Utilities"),
                            ("turnover", "Turnover"),
                            ("repair_maintenance", "Repair & maintenance"),
                            ("professional_services", "Professional services"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="High-level grouping for reporting and intelligence.",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional internal description of how this category should be used.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the category is active for new expense assignment.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Optional UI/report ordering value."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to="core.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent category for hierarchical classification.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="expenses.expensecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense category",
                "verbose_name_plural": "Expense categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Vendor or payee display name.", max_length=200
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("contractor", "Contractor"),
                            ("utility", "Utility"),
                            ("government", "Government"),
                            ("insurance", "Insurance"),
                            ("software", "Software"),
                            ("management", "Management"),
                            ("supplier", "Supplier"),
                            ("professional", "Professional"),
                            ("other", "Other"),
                        ],
                        help_text="Optional classification for reporting and filtering.",
                        max_length=50,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional contact person name.",
                        max_length=120,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional vendor email address.",
                        max_length=254,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optional vendor phone number.",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about the vendor."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the vendor is active for new expense assignment.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("building", "Building"),
                            ("unit", "Unit"),
                            ("lease", "Lease"),
                        ],
                        help_text="Structural scope of this expense record.",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short human-readable expense title.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional structured description or memo."
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive expense amount stored as Decimal.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        help_text="Primary reporting date for when the expense occurred."
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional due date for unpaid/submitted expenses.",
                        null=True,
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the expense was paid, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("due", "Due"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Operational state of the expense.",
                        max_length=20,
                    ),
                ),
                (
                    "is_reimbursable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this expense is eligible for reimbursement tracking.",
                    ),
                ),
                (
                    "reimbursement_status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not applicable"),
                            ("reimbursable", "Reimbursable"),
                            ("submitted", "Submitted"),
                            ("reimbursed", "Reimbursed"),
                        ],
                        default="not_applicable",
                        help_text="Reimbursement workflow state.",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Optional vendor invoice or bill number.",
                        max_length=120,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="Optional import/reference id from an external system.",
                        max_length=120,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes not intended to replace structured data.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("import", "Import"),
                            ("system", "System"),
                            ("ai_suggested", "AI suggested"),
                        ],
                        default="manual",
                        help_text="How this expense entered the system.",
                        max_length=20,
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-archive flag used to hide inactive records from default views.",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp for when the record was archived.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        help_text="Building scope or derived building for lease-scoped expenses.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="buildings.building",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lease reference for lease-scoped expenses.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="core.organization",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unit scope or derived unit for lease-scoped expenses.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="buildings.unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional structured category for reporting and intelligence.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expenses.expensecategory",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional payee/vendor reference.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expenses.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-expense_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded attachment file.",
                        upload_to="expense_attachments/%Y/%m/",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        help_text="Original client-side filename if captured.",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="Optional MIME type metadata.",
                        max_length=100,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Optional file size in bytes.", null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="expenses.expense",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_attachments",
                        to="core.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_expense_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense attachment",
                "verbose_name_plural": "Expense attachments",
                "ordering": ["-uploaded_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["organization", "expense"],
                        name="expenses_ex_organiz_2b14a4_idx",
                    ),
                    models.Index(
                        fields=["organization", "uploaded_at"],
                        name="expenses_ex_organiz_040df9_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="expensecategory",
            index=models.Index(
                fields=["organization", "is_active"],
                name="expenses_ex_organiz_3796f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expensecategory",
            index=models.Index(
                fields=["organization", "kind"], name="expenses_ex_organiz_d49510_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expensecategory",
            index=models.Index(
                fields=["organization", "name"], name="expenses_ex_organiz_91ce6a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="expensecategory",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["organization", "is_active"],
                name="expenses_ve_organiz_6364ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["organization", "vendor_type"],
                name="expenses_ve_organiz_854673_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["organization", "name"], name="expenses_ve_organiz_5bf29c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendor",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["organization", "expense_date"],
                name="expenses_ex_organiz_974c03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["organization", "status", "due_date"],
                name="expenses_ex_organiz_825d6e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["organization", "scope", "expense_date"],
                name="expenses_ex_organiz_069314_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["organization", "building", "expense_date"],
                name="expenses_ex_organiz_16a416_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["organization", "unit", "expense_date"],
                name="expenses_ex_organiz_89e62c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["organization", "lease", "expense_date"],
                name="expenses_ex_organiz_1a9d05_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["organization", "category", "expense_date"],
                name="expenses_ex_organiz_687db5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["organization", "vendor", "expense_date"],
                name="expenses_ex_organiz_09fad0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["organization", "is_archived", "expense_date"],
                name="expenses_ex_organiz_319ec4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="expenses_expense_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit__isnull", True), ("building__isnull", False), _connector="OR"
                ),
                name="expenses_expense_unit_requires_building",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("scope", "organization"),
                        ("building__isnull", True),
                        ("unit__isnull", True),
                        ("lease__isnull", True),
                    ),
                    models.Q(("scope", "organization"), _negated=True),
                    _connector="OR",
                ),
                name="expenses_expense_org_scope_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("scope", "building"),
                        ("building__isnull", False),
                        ("unit__isnull", True),
                        ("lease__isnull", True),
                    ),
                    models.Q(("scope", "building"), _negated=True),
                    _connector="OR",
                ),
                name="expenses_expense_building_scope_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("scope", "unit"),
                        ("building__isnull", False),
                        ("unit__isnull", False),
                        ("lease__isnull", True),
                    ),
                    models.Q(("scope", "unit"), _negated=True),
                    _connector="OR",
                ),
                name="expenses_expense_unit_scope_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "lease"), ("lease__isnull", False)),
                    models.Q(("scope", "lease"), _negated=True),
                    _connector="OR",
                ),
                name="expenses_expense_lease_scope_shape",
            ),
        ),
    ]
