# Generated by Django 5.2.11 on 2026-03-22 19:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="expensecategory",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="vendor",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"),
                name="expenses_category_org_slug_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("organization"),
                name="expenses_category_org_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("organization"),
                name="expenses_vendor_org_name_ci_unique",
            ),
        ),
    ]
