# Generated by Django 5.2.1 on 2026-02-19 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("leases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("rent", "Rent"),
                            ("late_fee", "Late fee"),
                            ("misc", "Misc"),
                        ],
                        help_text="The type of charge (rent, late fee, misc).",
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount owed for this charge. Must be > 0.",
                        max_digits=12,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Date the charge is due. Used for delinquency and FIFO allocation ordering."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional internal note (e.g. 'March rent', 'Fee assessed due to NSF check').",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server timestamp when the charge record was created.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the charge (if created manually/admin).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        help_text="The lease that owns this charge (rent/fees for this lease).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant boundary. Every charge belongs to exactly one organization.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount received. Must be > 0.",
                        max_digits=12,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        help_text="When funds were received (not when entered into the system)."
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("zelle", "Zelle"),
                            ("ach", "ACH"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="How the payment was received (cash, Zelle, ACH, check, etc.).",
                        max_length=16,
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional reference ID (check #, Zelle confirmation, bank memo, etc.).",
                        max_length=128,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional internal note (e.g. 'Partial payment', 'Paid by roommate').",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server timestamp when the payment record was created.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded the payment.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        help_text="The lease this payment is associated with.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant boundary. Every payment belongs to exactly one organization.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount applied from the payment to the charge. Must be > 0.",
                        max_digits=12,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server timestamp when the allocation record was created.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant boundary. Every allocation belongs to exactly one organization.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="core.organization",
                    ),
                ),
                (
                    "charge",
                    models.ForeignKey(
                        help_text="The charge that is being paid down by this allocation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="billing.charge",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        help_text="The payment providing funds for this allocation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="billing.payment",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="charge",
            index=models.Index(
                fields=["organization", "created_at"],
                name="billing_cha_organiz_abb468_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="charge",
            index=models.Index(
                fields=["organization", "lease", "due_date"],
                name="billing_cha_organiz_16cc9a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="charge",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="billing_charge_amount_gt_0"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "created_at"],
                name="billing_pay_organiz_0557ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "lease", "paid_at"],
                name="billing_pay_organiz_92429e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="billing_payment_amount_gt_0",
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["organization", "created_at"],
                name="billing_all_organiz_b677f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["organization", "payment"],
                name="billing_all_organiz_8e618f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["organization", "charge"], name="billing_all_organiz_7bda64_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="billing_allocation_amount_gt_0",
            ),
        ),
    ]
