# Generated by Django 5.2.1 on 2026-02-20 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("core", "0001_initial"),
        ("leases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="charge",
            constraint=models.UniqueConstraint(
                fields=("organization", "lease", "kind", "due_date"),
                name="billing_unique_charge_per_kind_due_date",
            ),
        ),
    ]
