# Generated by Django 5.2.11 on 2026-03-30 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_charge_billing_unique_charge_per_kind_due_date"),
        ("leases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocation",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount applied from the payment to the charge. Must be greater than zero.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="charge",
            field=models.ForeignKey(
                help_text="The charge being paid down by this allocation.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="billing.charge",
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Server timestamp when this allocation was created.",
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount owed for this charge. Must be greater than zero.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Server timestamp when this charge was created.",
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the charge.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charges_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="due_date",
            field=models.DateField(
                help_text="Due date used for delinquency and payment application order."
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="kind",
            field=models.CharField(
                choices=[("rent", "Rent"), ("late_fee", "Late fee"), ("misc", "Misc")],
                help_text="The charge type, such as rent, late fee, or misc.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="lease",
            field=models.ForeignKey(
                help_text="The lease that owns this charge.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charges",
                to="leases.lease",
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional internal note for this charge.",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount received. Must be greater than zero.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Server timestamp when this payment was created.",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="external_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional external reference such as check number or transfer note.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("zelle", "Zelle"),
                    ("ach", "ACH"),
                    ("check", "Check"),
                    ("venmo", "Venmo"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="How the payment was received.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional internal note for this payment.",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(
                help_text="When funds were received, not when the record was entered."
            ),
        ),
    ]
