from __future__ import annotations

DEMO_BUILDING_SCENARIOS = [
    {
        "code": "MAPLE",
        "name": "Maple Court",
        "building_type": "MULTI_FAMILY",
        "address_line1": "1458 Dean St",
        "city": "Brooklyn",
        "state": "NY",
        "postal_code": "11213",
        "country": "US",
        "units": [
            {
                "code": "MAPLE-1A",
                "label": "1A",
                "bedrooms": 2,
                "bathrooms": 1.0,
                "sqft": 850,
            },
            {
                "code": "MAPLE-1B",
                "label": "1B",
                "bedrooms": 2,
                "bathrooms": 1.0,
                "sqft": 875,
            },
            {
                "code": "MAPLE-1C",
                "label": "1C",
                "bedrooms": 1,
                "bathrooms": 1.0,
                "sqft": 650,
            },
            {
                "code": "MAPLE-2A",
                "label": "2A",
                "bedrooms": 3,
                "bathrooms": 2.0,
                "sqft": 1100,
            },
        ],
    },
    {
        "code": "RIVER",
        "name": "River Bend",
        "building_type": "MULTI_FAMILY",
        "address_line1": "34-12 30th Ave",
        "city": "Astoria",
        "state": "NY",
        "postal_code": "11103",
        "country": "US",
        "units": [
            {
                "code": "RIVER-2A",
                "label": "2A",
                "bedrooms": 2,
                "bathrooms": 1.0,
                "sqft": 900,
            },
            {
                "code": "RIVER-2B",
                "label": "2B",
                "bedrooms": 2,
                "bathrooms": 1.0,
                "sqft": 925,
            },
            {
                "code": "RIVER-3A",
                "label": "3A",
                "bedrooms": 1,
                "bathrooms": 1.0,
                "sqft": 700,
            },
            {
                "code": "RIVER-3B",
                "label": "3B",
                "bedrooms": 1,
                "bathrooms": 1.0,
                "sqft": 720,
            },
        ],
    },
    {
        "code": "OAK",
        "name": "Oak Terrace",
        "building_type": "TOWNHOUSE",
        "address_line1": "1028 Washington Ave",
        "city": "Bronx",
        "state": "NY",
        "postal_code": "10456",
        "country": "US",
        "units": [
            {
                "code": "OAK-1",
                "label": "1",
                "bedrooms": 3,
                "bathrooms": 2.0,
                "sqft": 1200,
            },
            {
                "code": "OAK-2",
                "label": "2",
                "bedrooms": 2,
                "bathrooms": 1.5,
                "sqft": 980,
            },
            {
                "code": "OAK-3",
                "label": "3",
                "bedrooms": 2,
                "bathrooms": 1.0,
                "sqft": 950,
            },
            {
                "code": "OAK-4",
                "label": "4",
                "bedrooms": 1,
                "bathrooms": 1.0,
                "sqft": 680,
            },
        ],
    },
    {
        "code": "HARBOR",
        "name": "Harbor Flats",
        "building_type": "CONDO",
        "address_line1": "55 St Nicholas Ave",
        "city": "Manhattan",
        "state": "NY",
        "postal_code": "10026",
        "country": "US",
        "units": [
            {
                "code": "HARBOR-A",
                "label": "A",
                "bedrooms": 2,
                "bathrooms": 2.0,
                "sqft": 1020,
            },
            {
                "code": "HARBOR-B",
                "label": "B",
                "bedrooms": 2,
                "bathrooms": 1.0,
                "sqft": 880,
            },
            {
                "code": "HARBOR-C",
                "label": "C",
                "bedrooms": 1,
                "bathrooms": 1.0,
                "sqft": 640,
            },
            {
                "code": "HARBOR-D",
                "label": "D",
                "bedrooms": 3,
                "bathrooms": 2.0,
                "sqft": 1180,
            },
        ],
    },
]
