# Filename: backend/apps/demo_data/scenarios/leases.py

from __future__ import annotations

DEMO_LEASE_SCENARIOS = [
    # MAPLE-1A: turnover history, currently occupied
    {
        "code": "LEASE-MAPLE-1A-2021",
        "unit_code": "MAPLE-1A",
        "tenant_code": "TENANT-JORDAN-ELLIS",
        "start_date": "2021-04-01",
        "end_date": "2022-03-31",
        "rent_amount": "1650.00",
        "security_deposit_amount": "1650.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-MAPLE-1A-2022",
        "unit_code": "MAPLE-1A",
        "tenant_code": "TENANT-MAYA-BROOKS",
        "start_date": "2022-05-01",
        "end_date": "2023-04-30",
        "rent_amount": "1725.00",
        "security_deposit_amount": "1725.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-MAPLE-1A-2023",
        "unit_code": "MAPLE-1A",
        "tenant_code": "TENANT-AVA-MITCHELL",
        "start_date": "2023-06-01",
        "end_date": None,
        "rent_amount": "1895.00",
        "security_deposit_amount": "1895.00",
        "rent_due_day": 1,
        "status": "active",
    },

    # MAPLE-1B: partial-payment current lease
    {
        "code": "LEASE-MAPLE-1B-2021",
        "unit_code": "MAPLE-1B",
        "tenant_code": "TENANT-LIAM-FOSTER",
        "start_date": "2021-04-01",
        "end_date": "2022-08-31",
        "rent_amount": "1750.00",
        "security_deposit_amount": "1750.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-MAPLE-1B-2022",
        "unit_code": "MAPLE-1B",
        "tenant_code": "TENANT-ETHAN-COLE",
        "start_date": "2022-10-01",
        "end_date": None,
        "rent_amount": "2100.00",
        "security_deposit_amount": "2100.00",
        "rent_due_day": 1,
        "status": "active",
    },

    # MAPLE-1C: currently vacant after prior lease
    {
        "code": "LEASE-MAPLE-1C-2021",
        "unit_code": "MAPLE-1C",
        "tenant_code": "TENANT-SOFIA-RIVERA",
        "start_date": "2021-06-01",
        "end_date": "2022-05-31",
        "rent_amount": "1450.00",
        "security_deposit_amount": "1450.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-MAPLE-1C-2022",
        "unit_code": "MAPLE-1C",
        "tenant_code": "TENANT-NOAH-BENNETT",
        "start_date": "2022-08-01",
        "end_date": "2024-01-31",
        "rent_amount": "1525.00",
        "security_deposit_amount": "1525.00",
        "rent_due_day": 1,
        "status": "ended",
    },

    # MAPLE-2A: stable family unit
    {
        "code": "LEASE-MAPLE-2A-2021",
        "unit_code": "MAPLE-2A",
        "tenant_code": "TENANT-EMMA-REED",
        "start_date": "2021-04-01",
        "end_date": "2023-03-31",
        "rent_amount": "2200.00",
        "security_deposit_amount": "2200.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-MAPLE-2A-2023",
        "unit_code": "MAPLE-2A",
        "tenant_code": "TENANT-OWEN-BAILEY",
        "start_date": "2023-05-01",
        "end_date": None,
        "rent_amount": "2450.00",
        "security_deposit_amount": "2450.00",
        "rent_due_day": 1,
        "status": "active",
    },

    # RIVER-2A: healthy current lease
    {
        "code": "LEASE-RIVER-2A-2021",
        "unit_code": "RIVER-2A",
        "tenant_code": "TENANT-NINA-PATEL",
        "start_date": "2021-07-01",
        "end_date": None,
        "rent_amount": "1750.00",
        "security_deposit_amount": "1750.00",
        "rent_due_day": 5,
        "status": "active",
    },

    # RIVER-2B: delinquent current lease after prior tenant
    {
        "code": "LEASE-RIVER-2B-2021",
        "unit_code": "RIVER-2B",
        "tenant_code": "TENANT-CHLOE-HAYES",
        "start_date": "2021-04-01",
        "end_date": "2022-12-31",
        "rent_amount": "1825.00",
        "security_deposit_amount": "1825.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-RIVER-2B-2023",
        "unit_code": "RIVER-2B",
        "tenant_code": "TENANT-CALEB-TURNER",
        "start_date": "2023-02-01",
        "end_date": None,
        "rent_amount": "2300.00",
        "security_deposit_amount": "2300.00",
        "rent_due_day": 1,
        "status": "active",
    },

    # RIVER-3A: churn-heavy smaller unit
    {
        "code": "LEASE-RIVER-3A-2021",
        "unit_code": "RIVER-3A",
        "tenant_code": "TENANT-HENRY-WARD",
        "start_date": "2021-05-01",
        "end_date": "2022-04-30",
        "rent_amount": "1350.00",
        "security_deposit_amount": "1350.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-RIVER-3A-2022",
        "unit_code": "RIVER-3A",
        "tenant_code": "TENANT-GRACE-MORGAN",
        "start_date": "2022-07-01",
        "end_date": "2023-06-30",
        "rent_amount": "1425.00",
        "security_deposit_amount": "1425.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-RIVER-3A-2023",
        "unit_code": "RIVER-3A",
        "tenant_code": "TENANT-JACKSON-PRICE",
        "start_date": "2023-09-01",
        "end_date": None,
        "rent_amount": "1550.00",
        "security_deposit_amount": "1550.00",
        "rent_due_day": 1,
        "status": "active",
    },

    # RIVER-3B: currently vacant, but recent history exists
    {
        "code": "LEASE-RIVER-3B-2021",
        "unit_code": "RIVER-3B",
        "tenant_code": "TENANT-LILY-COOPER",
        "start_date": "2021-04-01",
        "end_date": "2022-03-31",
        "rent_amount": "1325.00",
        "security_deposit_amount": "1325.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-RIVER-3B-2022",
        "unit_code": "RIVER-3B",
        "tenant_code": "TENANT-LEO-RAMOS",
        "start_date": "2022-06-01",
        "end_date": "2024-02-29",
        "rent_amount": "1475.00",
        "security_deposit_amount": "1475.00",
        "rent_due_day": 1,
        "status": "ended",
    },

    # OAK-1: premium larger unit
    {
        "code": "LEASE-OAK-1-2021",
        "unit_code": "OAK-1",
        "tenant_code": "TENANT-ZOE-PERRY",
        "start_date": "2021-04-01",
        "end_date": None,
        "rent_amount": "2650.00",
        "security_deposit_amount": "2650.00",
        "rent_due_day": 3,
        "status": "active",
    },

    # OAK-2: stable mid-market unit
    {
        "code": "LEASE-OAK-2-2021",
        "unit_code": "OAK-2",
        "tenant_code": "TENANT-WYATT-HUGHES",
        "start_date": "2021-08-01",
        "end_date": None,
        "rent_amount": "1950.00",
        "security_deposit_amount": "1950.00",
        "rent_due_day": 1,
        "status": "active",
    },

    # OAK-3: ended then renewed with new tenant
    {
        "code": "LEASE-OAK-3-2021",
        "unit_code": "OAK-3",
        "tenant_code": "TENANT-HANNAH-KELLY",
        "start_date": "2021-04-01",
        "end_date": "2023-08-31",
        "rent_amount": "1850.00",
        "security_deposit_amount": "1850.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-OAK-3-2023",
        "unit_code": "OAK-3",
        "tenant_code": "TENANT-JORDAN-ELLIS",
        "start_date": "2023-10-01",
        "end_date": None,
        "rent_amount": "2050.00",
        "security_deposit_amount": "2050.00",
        "rent_due_day": 1,
        "status": "active",
    },

    # OAK-4: smaller unit with vacancy gap and current tenant
    {
        "code": "LEASE-OAK-4-2021",
        "unit_code": "OAK-4",
        "tenant_code": "TENANT-MAYA-BROOKS",
        "start_date": "2021-09-01",
        "end_date": "2022-08-31",
        "rent_amount": "1250.00",
        "security_deposit_amount": "1250.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-OAK-4-2023",
        "unit_code": "OAK-4",
        "tenant_code": "TENANT-AVA-MITCHELL",
        "start_date": "2023-01-01",
        "end_date": None,
        "rent_amount": "1395.00",
        "security_deposit_amount": "1395.00",
        "rent_due_day": 1,
        "status": "active",
    },

    # HARBOR-A: healthy newer premium lease
    {
        "code": "LEASE-HARBOR-A-2022",
        "unit_code": "HARBOR-A",
        "tenant_code": "TENANT-ETHAN-COLE",
        "start_date": "2022-03-01",
        "end_date": None,
        "rent_amount": "2350.00",
        "security_deposit_amount": "2350.00",
        "rent_due_day": 5,
        "status": "active",
    },

    # HARBOR-B: ended then current tenant
    {
        "code": "LEASE-HARBOR-B-2021",
        "unit_code": "HARBOR-B",
        "tenant_code": "TENANT-NINA-PATEL",
        "start_date": "2021-04-01",
        "end_date": "2023-03-31",
        "rent_amount": "1885.00",
        "security_deposit_amount": "1885.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-HARBOR-B-2023",
        "unit_code": "HARBOR-B",
        "tenant_code": "TENANT-CALEB-TURNER",
        "start_date": "2023-06-01",
        "end_date": None,
        "rent_amount": "2140.00",
        "security_deposit_amount": "2140.00",
        "rent_due_day": 1,
        "status": "active",
    },

    # HARBOR-C: historically occupied, currently vacant
    {
        "code": "LEASE-HARBOR-C-2021",
        "unit_code": "HARBOR-C",
        "tenant_code": "TENANT-SOFIA-RIVERA",
        "start_date": "2021-04-01",
        "end_date": "2022-06-30",
        "rent_amount": "1295.00",
        "security_deposit_amount": "1295.00",
        "rent_due_day": 1,
        "status": "ended",
    },
    {
        "code": "LEASE-HARBOR-C-2022",
        "unit_code": "HARBOR-C",
        "tenant_code": "TENANT-NOAH-BENNETT",
        "start_date": "2022-09-01",
        "end_date": "2024-11-30",
        "rent_amount": "1425.00",
        "security_deposit_amount": "1425.00",
        "rent_due_day": 1,
        "status": "ended",
    },

    # HARBOR-D: large unit with stable long-term tenant
    {
        "code": "LEASE-HARBOR-D-2021",
        "unit_code": "HARBOR-D",
        "tenant_code": "TENANT-EMMA-REED",
        "start_date": "2021-04-01",
        "end_date": None,
        "rent_amount": "2750.00",
        "security_deposit_amount": "2750.00",
        "rent_due_day": 1,
        "status": "active",
    },
]